//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet
    {

		public int Id { get; set; }
        public double Weight { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Depth { get; set; }
        public System.DateTime DataProduction { get; set; }
        public System.DateTime DataExpiration { get; set; }
		public double Volume { get; set; }


		#region Конструкторы
		public Pallet(int id, double length, double width, double depth, DateTime dataProduction)
		{
			Id = id;
			Weight = 30;
			Length = length;
			Width = width;
			Depth = depth;
			DataProduction = dataProduction;
		}
		public Pallet(int id, double weight, double length, double width, double depth, DateTime dataProduction, DateTime dataExpiration)
		{
			Id = id;
			Weight = weight;
			Length = length;
			Width = width;
			Depth = depth;
			DataProduction = dataProduction;
			DataExpiration = dataExpiration;
		}
		#endregion
	}
}
