//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonopolyWPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public int Id { get; set; }
        public double Weight { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Depth { get; set; }
        public System.DateTime DataProduction { get; set; }
        public Nullable<System.DateTime> DataExpiration { get; set; }
        public int PalletID { get; set; }
        public Nullable<double> Volume { get; set; }

		#region Конструкторы
		static Random r;
		static Box()
		{
			r = new Random();
		}

		public Box() { }
		public Box(int id, double weight, double length, double width, double depth, DateTime dataProduction)
		{
			Id = id;
			Weight = weight;
			Length = length;
			Width = width;
			Depth = depth;
			DataProduction = dataProduction;
			DataExpiration = dataProduction.AddDays(100);
			PalletID = r.Next(1, 6);
		}
		public Box(int id, double weight, double length, double width, double depth, DateTime dataProduction, int palletID)
		{
			Id = id;
			Weight = weight;
			Length = length;
			Width = width;
			Depth = depth;
			DataProduction = dataProduction;
			DataExpiration = dataProduction.AddDays(100);
			PalletID = palletID;
		}
		public Box(int id, double weight, double length, double width, double depth, DateTime dataProduction, DateTime dataExpiration, int palletID)
		{
			Id = id;
			Weight = weight;
			Length = length;
			Width = width;
			Depth = depth;
			DataProduction = dataProduction;
			DataExpiration = dataExpiration;
			PalletID = palletID;
		}
		#endregion
	}
}
