//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonopolyWPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet
    {
        public int Id { get; set; }
        public Nullable<double> Weight { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Depth { get; set; }
        public System.DateTime DataProduction { get; set; }
        public Nullable<System.DateTime> DataExpiration { get; set; }
        public Nullable<double> Volume { get; set; }

		#region Конструкторы
		public Pallet() { }
		public Pallet(int id, double length, double width, double depth, DateTime dataProduction)
		{
			Id = id;
			Weight = 30;
			Length = length;
			Width = width;
			Depth = depth;
			DataProduction = dataProduction;
		}
		public Pallet(int id, double weight, double length, double width, double depth, DateTime dataProduction, DateTime dataExpiration)
		{
			Id = id;
			Weight = weight;
			Length = length;
			Width = width;
			Depth = depth;
			DataProduction = dataProduction;
			DataExpiration = dataExpiration;
		}

		public Pallet(int id, double? weight, double length, double width, double depth, DateTime dataProduction, DateTime? dataExpiration, double? volume)
		{
			Id = id;
			Weight = weight;
			Length = length;
			Width = width;
			Depth = depth;
			DataProduction = dataProduction;
			DataExpiration = dataExpiration;
			Volume = volume;
		}
		#endregion
	}
}
